FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3 python3-pip

RUN python3 -m pip install \
                    jupyter \
                    tensorflow-gpu \
                    pandas \
                    keras

RUN useradd -ms /bin/bash me
USER me
WORKDIR /home/me

COPY fra.txt /home/me/fra.txt
COPY dictionary-gpu.ipynb /home/me/dictionary-gpu.ipynb
ENTRYPOINT jupyter notebook --ip=0.0.0.0
# --NotebookApp.token='' --NotebookApp.password=''
